modLoader="javafml"
loaderVersion="$forgefmlrange"
issueTrackerURL="https://github.com/${github}/issues"
license="$license"
logoFile="pack.png"

[[mods]]
    modId="$id"
    version="$version"
    displayName="$simplename"
    displayTest="IGNORE_SERVER_VERSION"
    updateJSONURL="https://forge.curseupdate.com/1395870/watermedia-yt-plugin"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia-yt-plugin"
    credits="$credits"
    authors="$authors"
    logoFile="pack.png"
    description='''$description'''

[[dependencies.${id}]]
    modId="watermedia"
    mandatory=true
    ordering="BEFORE"
    side="CLIENT"
    versionRange="[2.1.37,2.2)"